sim: make local variable 'const'
This build error was reported to me off list:

  common/callback.c:993:13: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
    993 |       char *q = strchr (m, ',');
        |             ^   ~~~~~~~~~~~~~~~

This is because with C23, strchr returns 'const char *' if a 'const
char *' is passed as an argument.

In this case M is 'const char *', so Q should also be 'const char *'.
And indeed, we don't write via Q at any time, so lets make it 'const'.

There should be no user visible changes after this commit.