Error compiling libctf-regression test
Seen on 64-bit targets.
ERROR: compilation of lookup program .../libctf-regression/gzrewrite.c failed

	* testsuite/libctf-regression/gzrewrite.c (main): Use %zu to
	print size_t values.
	* testsuite/libctf-regression/zrewrite.c (main): Likewise.