Avoid expect's buffer overflow in info-var.exp test.
Once the executable is started, info variables can show thousands
of variables belonging to glibc (see below).

This long list of variables then causes the test to fail, due
to expect's buffer overflow:
  Running /bd/home/philippe/gdb/git/build_binutils-gdb/gdb/testsuite/../../../binutils-gdb/gdb/testsuite/gdb.base/info-var.exp ...
  ERROR: internal buffer is full.
  ERROR: internal buffer is full.
  ERROR: internal buffer is full.

Fix this by testing 'info variables' without running the executable.

gdb ./info-var
...
Reading symbols from ./info-var...
(gdb) |info variables|wc
     27      54     971
(gdb) start
Temporary breakpoint 1 at 0x1129: file /bd/home/philippe/gdb/git/build_binutils-gdb/gdb/testsuite/../../../binutils-gdb/gdb/testsuite/gdb.base/info-var-f1.c, line 23.
Starting program: /bd/home/philippe/gdb/git/build_binutils-gdb/gdb/testsuite/outputs/gdb.base/info-var/info-var

Temporary breakpoint 1, main ()
    at /bd/home/philippe/gdb/git/build_binutils-gdb/gdb/testsuite/../../../binutils-gdb/gdb/testsuite/gdb.base/info-var-f1.c:23
23	  return global_var + get_offset() + f1_var;
(gdb) |info variables|wc
   4334   14581  130738
(gdb)

gdb/testsuite/ChangeLog
2019-09-04  Philippe Waroquiers  <philippe.waroquiers@skynet.be>

	* gdb.base/info-var.exp: Test info variables without running
	to main, to avoid expect's buffer overflow.