Fix s390 GNU/Linux build
- Fixes this compile error:

  ../../src/gdb/s390-linux-nat.c:125:8: error: ‘virtual bool s390_linux_nat_target::have_continuable_watchpoint()’ can be marked override [-Werror=suggest-override]
     bool have_continuable_watchpoint () { return 1; }
	  ^~~~~~~~~~~~~~~~~~~~~~~~~~~

  s390 never implemented that hook.  The declaration of the method got
  there simply via copy/paste from some other target.

  Return 'true' instead of '1' while at it.

- Fixes this link error:

  s390-linux-nat.o:(.rodata._ZTV21s390_linux_nat_target[_ZTV21s390_linux_nat_target]+0x120): undefined reference to `s390_linux_nat_target::watchpoint_addr_within_range(unsigned long, unsigned long, int)'

gdb/ChangeLog:
2018-05-03  Pedro Alves  <palves@redhat.com>

	* s390-linux-nat.c
	(s390_linux_nat_target::have_continuable_watchpoint): Mark with
	override.  Write 'true' instead of '1'.
	(s390_linux_nat_target::watchpoint_addr_within_range): Remove
	declaration.