Unbreak PPC gdb builds
Commit f486487f5586 (Mostly trivial enum fixes) missed updating
ppc-linux-nat.c, resulting in:

 ../../src/gdb/ppc-linux-nat.c: In function ‘_initialize_ppc_linux_nat’:
 ../../src/gdb/ppc-linux-nat.c:2503:27: error: assignment from incompatible pointer type [-Werror]
 ../../src/gdb/ppc-linux-nat.c:2504:27: error: assignment from incompatible pointer type [-Werror]

gdb/ChangeLog
2015-08-02  Pedro Alves  <palves@redhat.com>

	* ppc-linux-nat.c (get_trigger_type, create_watchpoint_request)
	(ppc_linux_insert_watchpoint, ppc_linux_remove_watchpoint): Change
	parameter 'rw's type to enum target_hw_bp_type and rename to
	'type'.