binutils fails to compile on AIX due to mismatched declaration
rs6000-core.c:280:19: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 const bfd_cleanup rs6000coff_core_p (bfd *abfd);
                   ^~~~~~~~~~~~~~~~~
rs6000-core.c:336:1: error: conflicting types for 'rs6000coff_core_p'
 rs6000coff_core_p (bfd *abfd)
 ^~~~~~~~~~~~~~~~~
rs6000-core.c:280:19: note: previous declaration of 'rs6000coff_core_p' was here
 const bfd_cleanup rs6000coff_core_p (bfd *abfd);
                   ^~~~~~~~~~~~~~~~~

	* rs6000-core.c (rs6000coff_core_p): Correct prototype.