[gdb/testsuite] Require python in gdb.dap/basic-dap.exp
When running test-case gdb.dap/basic-dap.exp with a gdb without python
support, I run into:
...
builtin_spawn gdb -nw -nx -iex set height 0 -iex set width 0 \
  -data-directory data-directory -iex set debug dap-log-file dap.log.1 -q \
  -i=dap
>>> {"seq": 1, "type": "request", "command": "initialize"}
Interpreter `dap' unrecognized
ERROR: eof reading json header
...

Fix this by requiring python in the test-case.

Tested on x86_64-linux, both with a gdb without and with python.