sim: testsuite: Fix build with host GCC15
Simulator testsuite build started failing with host GCC-15:

  bits-tst.c:323:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
  bits-tst.c: In function ‘main’:
  bits-tst.c:323:1: error: old-style function definition [-Werror=old-style-definition]

Fix by including string.h to get the required prototypes, and changing
main's declaration to modern C.

Signed-off-by: Dimitar Dimitrov <dimitar@dinux.eu>
Approved-By: Tom Tromey <tom@tromey.com>