[gdb/testsuite] Require is_amd64_regs_target in gdb.base/disasm-optim.exp
When running test-case gdb.base/disasm-optim.exp with target board unix/-m32,
we get:
...
 Running disasm-optim.exp ...
 gdb compile failed, disasm-optim.c: Assembler messages:
 disasm-optim.c:35: Error: bad register name `%rip)'
 disasm-optim.c:46: Error: bad register name `%rax)'
 disasm-optim.c:57: Error: bad register name `%rip)'

                 === gdb Summary ===

 # of untested testcases         1
...

Fix this by requiring is_amd64_regs_target instead of istarget
"x86_64-*-linux*".

Tested on x86_64-linux.

gdb/testsuite/ChangeLog:

2021-01-12  Tom de Vries  <tdevries@suse.de>

	* gdb.base/disasm-optim.exp: Require is_amd64_regs_target.