gdb: fix build with newest clang
The upstream build of GDB can fail on fedora rawhide, since the self
check in regcache.c uses an unitialized variable to be compared, which
now generates the following warning:

    binutils-gdb/gdb/regcache.c:1847:42: error: variable
    'buf' is uninitialized when passed as a const pointer argument here
    [-Werror,-Wuninitialized-const-pointer]
    1847 | SELF_CHECK (regcache->raw_compare (0, &buf, register_size (inf.arch (), 0)));

This commit fixes that by initializing the variable to 0.
Since the comment above that line would be changed, it was also
reformatted so that it doesn't go beyond 80 columns.

Approved-By: Simon Marchi <simon.marchi@efficios.com>