gas: xtensa build failure with --enable-64-bit-bfd
A 32-bit host with --enable-64-bit-bfd --target=xtensa-lx106-elf give:
gas/config/tc-xtensa.c: In function ‘xg_get_best_chain_entry’:
gas/config/tc-xtensa.c:7689:11: error: absolute value function ‘labs’ given an argument of type ‘offsetT’ {aka ‘long long int’} but has parameter of type ‘long int’ which may cause truncation of value [-Werror=absolute-value]
 7689 |       if (labs (off) >= J_RANGE - J_MARGIN)
      |           ^~~~

Let's not use labs.  Unlike labs vma_abs deliberately returns an
unsigned value, and does the negation in an unsigned type so that
signed overflow can't happen.

	* config/tc-xtensa.c (vma_abs): New function.
	(xg_get_best_chain_entry, xg_get_fulcrum, xg_find_best_trampoline),
	(xg_is_relaxable_fixup): Use in place of labs.