gdb: include gdb_wait.h in gdb_wait.c
When building for mingw with -Wmissing-declarations, I get:

  CXX    gdbsupport/gdb_wait.o
/binutils-gdb/gdb/gdbsupport/gdb_wait.c:52:1: error: no previous declaration for 'int windows_status_to_termsig(long unsigned int)' [-Wer
ror=missing-declarations]
   52 | windows_status_to_termsig (unsigned long status)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~

Make gdb_wait.c include gdb_wait.h to fix it.

gdb/ChangeLog:

	* gdbsupport/gdb_wait.c: Include gdb_wait.h.