[gdb/testsuite] Fix gdb.server/unittest.exp with host board local-remote-host.exp
With test-case gdb.server/unittest.exp and host board local-remote-host.exp I
run into:
...
builtin_spawn build/gdbserver/gdbserver --selftest^M
ERROR: : spawn id exp7 not open
    while executing
"expect {
-i exp7 -timeout 10
    -i $server_spawn_id
    -re "Ran ($decimal) unit tests, 0 failed" {
        set num_ran $expect_out(1,string)
        gdb_assert "..."
    ("uplevel" body line 1)
    invoked from within
"uplevel $body" NONE : spawn id exp7 not open
UNRESOLVED: gdb.server/unittest.exp: unit tests
...

The problem is (as fixed for avr in commit df5b8876083 ("gdb/testsuite: better
handle failures in simavr board, reap simavr process")), that gdb_expect through
remote_expect adds a "-i <gdb spawn id> -timeout 10", which is the one causing
the error.

As in aforementioned commit, fix this by using expect instead.

Tested on x86_64-linux.