gdb: include <mutex> in dwarf2/read.h
The buildbot pointed out this compilation failure on AlmaLinux, with g++
8.5.0, which is not seen on more recent systems:

     CXX    gdbtypes.o
    In file included from ../../binutils-gdb/gdb/gdbtypes.c:39:
    ../../binutils-gdb/gdb/dwarf2/read.h:639:8: error: ‘mutex’ in namespace ‘std’ does not name a type
       std::mutex dwo_files_lock;
            ^~~~~
    ../../binutils-gdb/gdb/dwarf2/read.h:639:3: note: ‘std::mutex’ is defined in header ‘<mutex>’; did you forget to ‘#include <mutex>’?
    ../../binutils-gdb/gdb/dwarf2/read.h:35:1:
    +#include <mutex>

    ../../binutils-gdb/gdb/dwarf2/read.h:639:3:
       std::mutex dwo_files_lock;
       ^~~

Fix it by including <mutex> in dwarf2/read.h.

Change-Id: Iba334a3dad217c86841a5e804d0f386876f5ff2f