Fix the i386 build
Remove old, no longer needed and no longer valid extern.

../../gdb/i386-nbsd-tdep.c:58:12: error: 'i386nbsd_sc_reg_offset' was declared 'extern' and later 'static' [-fpermissive]
   58 | static int i386nbsd_sc_reg_offset[] =
      |            ^~~~~~~~~~~~~~~~~~~~~~
In file included from ../../gdb/i386-nbsd-tdep.c:31:
../../gdb/i386-tdep.h:480:12: note: previous declaration of 'i386nbsd_sc_reg_offset'
  480 | extern int i386nbsd_sc_reg_offset[];
      |            ^~~~~~~~~~~~~~~~~~~~~~

gdb/ChangeLog:

	* i386-tdep.h (i386nbsd_sc_reg_offset): Remove.