[gdb/build] Fix unused var in dwarf2/read.c
On x86_64-linux, with gcc 7.5.0 I ran into a build breaker:
...
gdb/dwarf2/read.c: In function ‘void read_comp_units_from_section()’:
gdb/dwarf2/read.c:4297:31: error: unused variable ‘sig_type_it’ \
  [-Werror=unused-variable]
    auto [sig_type_it, inserted] = sig_types.emplace (sig_ptr);
                               ^
...

Fix this by dropping the unused variable.

Tested on x86_64-linux, by completing a build.