Add virtual destructor to selftest
Clang 6 shows this warning

  In file included from /home/emaisin/src/binutils-gdb/gdb/common/selftest.c:19:
  In file included from /home/emaisin/src/binutils-gdb/gdb/common/common-defs.h:92:
  In file included from /home/emaisin/src/binutils-gdb/gdb/common/gdb_unique_ptr.h:23:
  In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/memory:81:
  /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:76:2: error: delete called on 'selftests::selftest' that is abstract but has non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
          delete __ptr;
          ^
  /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:236:4: note: in instantiation of member function 'std::default_delete<selftests::selftest>::operator()' requested here
            get_deleter()(__ptr);
            ^
  /home/emaisin/src/binutils-gdb/gdb/common/selftest.c:57:17: note: in instantiation of member function 'std::unique_ptr<selftests::selftest, std::default_delete<selftests::selftest> >::~unique_ptr' requested here
    tests[name] = std::unique_ptr<selftest> (test);
                  ^

The error is legitimate, we (the unique_ptr) are deleting selftest
objects through the base pointer, so technically the destructor should
be virtual, so that the destructor of the subclass is invoked.

gdb/ChangeLog:

	* common/selftest.h (struct selftest): Add virtual destructor.