[PR build/29791] gnulib: Disable _GL_ATTRIBUTE_DEALLOC on Solaris
gdbsupport compilation badly fails with GCC 12 on Solaris, with errors
like

../gnulib/config.h:1693:72: error: ‘malloc’ attribute argument 1 is ambiguous
 1693 | # define _GL_ATTRIBUTE_DEALLOC(f, i) __attribute__ ((__malloc__ (f, i)))
      |                                                                        ^
../gnulib/config.h:1693:72: note: use a cast to the expected type to disambiguate

We've not yet been able to determine where the ambiguity actually lies,
so this patch works around the issue by disabling _GL_ATTRIBUTE_DEALLOC
on Solaris, at least as a workaround for GDB 13.

As Tom suggested in the PR, this is done using our infrastructure for
local gnulib patches.

Tested on sparcv9-sun-solaris2.11, amd64-pc-solaris2.11, and
x86_64-pc-linux-gnu.

Approved-By: Simon Marchi <simon.marchi@efficios.com>