gnulib: import mkstemp
Older versions of MinGW do not support mkstemp causing:

    gdb/unittests/scoped_fd-selftests.c:37:29: error: \
    'mkstemp' was not declared in this scope
       int fd = mkstemp (filename);
                             ^
    gdb/unittests/scoped_fd-selftests.c: In function 'void
    selftests::scoped_fd::test_release()':
    gdb/unittests/scoped_fd-selftests.c:56:29: error: \
    'mkstemp' was not declared in this scope
       int fd = mkstemp (filename);
                             ^

Import mkstemp from gnulib.

gdb/
	* gnulib/update-gnulib.sh (IMPORTED_GNULIB_MODULES): Add mkstemp.
	* gnulib/aclocal.m4: Regenerated.
	* gnulib/config.in: Regenerated.
	* gnulib/configure: Regenerated.
	* gnulib/import/Makefile.am: Regenerated.
	* gnulib/import/Makefile.in: Regenerated.
	* gnulib/import/m4/gnulib-cache.m4: Regenerated.
	* gnulib/import/m4/gnulib-comp.m4: Regenerated.
	* gnulib/import/m4/mkstemp.m4: Imported.
	* gnulib/import/m4/secure_getenv.m4: Imported.
	* gnulib/import/m4/tempname.m4: Imported.
	* gnulib/import/mkstemp.c: Imported.
	* gnulib/import/secure_getenv.c: Imported.
	* gnulib/import/tempname.c: Imported.
	* gnulib/import/tempname.h: Imported.