testsuite: diagnose a running GDB in gdb_skip_xml_tests
If GDB is running when gdb_skip_xml_tests is called with
--target_board=native-extended-gdbserer.exp, it fails with:

    (gdb) FAIL: ....exp: set tdesc filename .../trivial.xml (got interactive prompt)
    monitor exit

Diagnose this in gdb_skip_xml_tests to generate a more meaningful error message:

    ERROR: tcl error sourcing ....exp.
    ERROR: GDB must not be running in gdb_skip_xml_tests.
        while executing
    [...]

testsuite/
	* lib/gdb.exp (gdb_skip_xml_tests): Error if GDB is running.