Remove unused variable in record-btrace.c
old_inferior_ptid is unused, this is caught by a gcc built from git
recently, not sure about previous versions:

/home/emaisin/src/binutils-gdb/gdb/record-btrace.c: In function ‘frame_info* get_thread_current_frame(thread_info*)’:
/home/emaisin/src/binutils-gdb/gdb/record-btrace.c:1974:10: error: unused variable ‘old_inferior_ptid’ [-Werror=unused-variable]
1974 |   ptid_t old_inferior_ptid;
     |          ^~~~~~~~~~~~~~~~~

gdb/ChangeLog:

	* record-btrace.c (get_thread_current_frame): Remove
	old_inferior_ptid.