Update libinproctrace.so path in lib/trace-support.exp
Following the move to gdbserver to the top-level, the path to
libinproctrace.so in testsuite/lib/trace-support.exp is no longer valid.
This can be observed by running:

    $ make check TESTS="gdb.trace/ftrace.exp" RUNTESTFLAGS="--target_board=native-gdbserver"
    ...
    ERROR: error copying "/home/smarchi/build/binutils-gdb/gdb/testsuite/../gdbserver/libinproctrace.so": no such file or directory

Adjust the path to libinproctrace.so by adding a "..".  With this patch,
the test mentioned above runs fine.

gdb/testsuite/ChangeLog:

	* lib/trace-support.exp (get_in_proc_agent): Adjust path to
	libinproctrace.so.