* emultempl/sunos.em (gld${EMULATION_NAME}_before_allocation): 	Don't make a shared library because of an undefined reference to 	__GLOBAL_OFFSET_TABLE_.