gdb: fix build of darwin-nat.c
Patch 743877128 ("gdb: remove regcache's address space") changed the
signature of darwin_nat_target::cancel_breakpoint, but missing updating
the class declaration, resulting in:

      CXX    darwin-nat.o
    /Users/smarchi/src/binutils-gdb/gdb/darwin-nat.c:1154:20: error: out-of-line definition of 'cancel_breakpoint' does not match any declaration in 'darwin_nat_target'
    darwin_nat_target::cancel_breakpoint (inferior *inf, ptid_t ptid)
                       ^~~~~~~~~~~~~~~~~
    /Users/smarchi/src/binutils-gdb/gdb/darwin-nat.c:1290:9: error: too many arguments to function call, expected single argument 'ptid', have 2 arguments
                                        ptid_t (inf->pid, 0, thread->gdb_port)))
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/smarchi/src/binutils-gdb/gdb/darwin-nat.h:129:7: note: 'cancel_breakpoint' declared here
      int cancel_breakpoint (ptid_t ptid);
          ^

Fix that.

Change-Id: Iedd58b36777eb77bca9e23f94882b217c9c87059