[gdbserver] Remove unused max_jump_pad_size
This patch is to remove max_jump_pad_size which isn't used else where,
and it causes a recent gcc warning like this,

gdb/gdbserver/tracepoint.c:2920:18: error: 'max_jump_pad_size' defined but not used [-Werror=unused-const-variable]
 static const int max_jump_pad_size = 0x100;
                  ^
cc1: all warnings being treated as errors

This variable max_jump_pad_size wasn't used since it was added in 2010
by https://sourceware.org/ml/gdb-patches/2010-06/msg00002.html

gdb/gdbserver:

2015-09-21  Yao Qi  <yao.qi@linaro.org>

	* tracepoint.c (max_jump_pad_size): Remove.