gdb/netbsd: fix fallout of thread_info ptr to ref change
Fix:

  CXX    netbsd-nat.o
/home/smarchi/src/binutils-gdb/gdb/netbsd-nat.c: In function 'void nbsd_resume(nbsd_nat_target*, ptid_t, int, gdb_signal)':
/home/smarchi/src/binutils-gdb/gdb/netbsd-nat.c:481:10: error: base operand of '->' has non-pointer type 'thread_info'
  481 |    if (tp->ptid.lwp () == ptid.lwp ())
      |          ^~

... following the changes that made thread iterators yield references
instead of points (e.g. 1ad8737b3c5 ("gdb: change inf_threads_iterator
to yield references")).

Change-Id: I6b96d1a81fbe8792e82e071c4871f0f212d2e49d